development:
  adapter: mysql2
  database: ror
  username: 0srrw6zexg82jts7866c
  host: eu-central.connect.psdb.cloud
  password: <%= ENV['ROR_PLANETSCALE_PASSWORD'] %>
  ssl_mode: verify_identity
  sslca: "/etc/ssl/certs/ca-certificates.crt"
